apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $.Values.gateway.name }}
spec:
  selector:
    istio: {{ $.Values.gateway.type }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ $.Values.virtualService.host | quote }}
